# Generated by Django 5.1.5 on 2025-01-29 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniones',
            fields=[
                ('codigo', models.CharField(default='CPBET-001', max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Ordinaria', 'Ordinaria'), ('Extraordinaria', 'Extraordinaria'), ('Directiva', 'Directiva')], max_length=50)),
            ],
            options={
                'verbose_name': 'Reunion',
                'verbose_name_plural': 'Reuniones',
                'db_table': 'Reuniones',
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.TextField(max_length=200, verbose_name='referencia domiciliaria')),
                ('celular', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('usuarios', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Multas_atr', 'Multas_atr'), ('Multas_ins', 'Multas_ins'), ('Aportes_mns', 'Aportes_mns'), ('Arriendo', 'Arriendo'), ('Aportes_x', 'Aportes_x')], help_text='concepto del cobro efectuado', max_length=50)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('fecha', models.DateField()),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.socios')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cuotas_catastrales', 'Cuotas_catastrales'), ('Mejoras_sede', 'Mejoras_sede'), ('Cuotas_aguapotable', 'Cuotas_aguapotable'), ('Cuotas_electricidad', 'Cuotas_electricidad'), ('Actividades_recreacionales', 'Actividades_recreacionales'), ('Cuotas_servicios_publicos', 'Cuotas_servicios_publicos'), ('Otros_egresos', 'Otros_egresos'), ('Ayudas_sociales', 'Ayudas_sociales')], help_text='concepto del gasto efectuado', max_length=80)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('fecha', models.DateField()),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.socios')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'db_table': 'Egresos',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No_Definido', 'No_Definido')], max_length=60)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Unión_Libre', 'Unión_Libre'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('No_Definido', 'No_Definido')], max_length=60)),
                ('cargo', models.CharField(choices=[('Socio', 'Socio'), ('Presidente', 'Presidente'), ('Vice_Presidente', 'Vice_Presidente'), ('Tesorero', 'Tesorero'), ('Secretario', 'Secretario'), ('Vocal', 'Vocal')], max_length=60)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desvinculado', 'Desvinculado'), ('Defunción', 'Defunción'), ('Inactivo', 'Inactivo')], max_length=60, verbose_name='cargo')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.socios')),
            ],
            options={
                'verbose_name': 'Detalle de Socio',
                'verbose_name_plural': 'Detalles de Socios',
                'db_table': 'Detalle_Socios',
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Asiste', 'Asiste'), ('Justificado', 'Justificado'), ('No_asiste', 'No_asiste'), ('Reemplazo', 'Reemplazo'), ('Atrasado', 'Atrasado')], max_length=60)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.reuniones')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.socios')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'Asistencias',
            },
        ),
    ]
